#!/bin/bash
set -e
#set -x

usage()
{
	echo "Usage: $0 b|c|f|d|n"
	echo "  Operation: b = build, c = clippy, f = cargo flash, d = dfu flash"
    exit 1
}

tgt="thumbv7em-none-eabihf"
chip="STM32F411CEUx"
dfu_opt="-a 0 -s 0x8000000"

flags="--release --target $tgt"
case "$1" in
B*|b*)
    set -x
    cargo build $flags
    ;;
C*|c*)
    set -x
    cargo clippy $flags
    ;;
F*|f*)
    set -x
    cargo flash $flags --chip $chip
    ;;
D*|d*)
    set -x
    cargo objcopy $flags -- -O binary target/out.bin
    set +x
    echo Boot the card in DFU mode and press Enter.
    read
    set -x
    dfu-util $dfu_opt -D target/out.bin
    ;;
*)
    usage
    ;;
esac
exit 0
# EOF
