[package]
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
edition = "2021"
readme = "README.md"
name = "vumeter-usb"
version = "0.1.0"


[features]
stm32f103 = []
stm32f411 = []
nrf52840 = []
default = ["blue_pill"]
# default = ["black_pill"]

blue_pill = ["stm32f103", "stm32f1xx-hal"]
black_pill = ["stm32f411", "stm32f4xx-hal"]
nucleo_f411 = ["stm32f411", "stm32f4xx-hal"]

[dependencies.stm32f1xx-hal]
optional = true
version = "0.9"
features = ["rt", "stm32f103"]

[dependencies.stm32f4xx-hal]
optional = true
version = "0.12"
features = ["rt", "stm32f411"]


[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-rtic = "1.0"
systick-monotonic = "1.0"
# cortex-m-rtic = { git = "https://github.com/rtic-rs/cortex-m-rtic.git" }
# systick-monotonic = { git = "https://github.com/rtic-rs/systick-monotonic.git" }
embedded-hal = "0.2"
stm32-usbd = "0.6"
usb-device = "0.2"
usbd-serial = "0.1"
panic-halt = "0.2"
fugit = "0.3"

# this lets you use `cargo fix`!
[[bin]]
name = "vumeter-usb"
test = false
bench = false

# identical profiles haha

[profile.release]
opt-level = 'z'
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations

[profile.dev]
opt-level = 'z'
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations
